# Generated by Django 3.1.1 on 2020-09-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favor',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
