# Generated by Django 3.1.1 on 2020-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='abstract',
            new_name='abstract_long',
        ),
        migrations.AddField(
            model_name='reports',
            name='abstract_short',
            field=models.TextField(default=None),
        ),
    ]
