# Generated by Django 3.1.1 on 2020-09-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_report',
            name='book_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='page_num',
            field=models.CharField(max_length=100),
        ),
    ]
