# Generated by Django 3.1.1 on 2020-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_summary_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary_report',
            name='book_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='issue_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='quote',
            field=models.IntegerField(default=0),
        ),
    ]
