# Generated by Django 3.1.1 on 2020-09-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200917_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary_report',
            name='page_num',
            field=models.IntegerField(default=0),
        ),
    ]
