# Generated by Django 3.1.1 on 2020-09-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200924_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_report',
            name='page_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
