# Generated by Django 3.1.1 on 2020-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200924_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_report',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='book_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='direct_urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='issue_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='issuer_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='issuer_kor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='journal_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='journal_kor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='keyword_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='keyword_kor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='quote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='sub_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary_report',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
