# Generated by Django 3.1.1 on 2020-09-21 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_first_favorites', to='favorites.favorites')),
                ('second_favorites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_second_favorites', to='favorites.favorites')),
                ('third_favorites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_third_favorites', to='favorites.favorites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
