# Generated by Django 3.1.1 on 2020-09-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20200922_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_favorites',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user_favorites',
            name='favorites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='favorites.favorites'),
        ),
    ]
