# Generated by Django 3.1.1 on 2020-09-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_auto_20200922_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_favorites',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='favorites.favorites'),
        ),
    ]
